### ISSUE TITLE
Prebuild event list page from static files

### ISSUE THREAD

**Issue by MiguelAlho** [agendaopensource/agendaopensource.github.io#5]
A possible idea - instead of submitting Issues with the info to later be integrated, what if it were a direct PR that adds a file with data and the jekyll build (somehow) would generate the underlying html? 

Not sure it is possible, but since jekyll prebuilds the pages, it could probable process a dataset to generate the desired page.

**Comment by t-lopes** [comment]
Not sure if we are talking about the same thing, but it's already supported. 
You are able to do a PR including the event in **_data/events.json** file.
I've used single JSON instead of multiple markdown files to make it easier to mantain.

Submitting issues is just an alternative for the ones that are not aware of github.
